name: CI Workflow

on: 
    issues:
        types: [opened]
    push:
    pull_request:

permissions:
    issues: write    

jobs:
    ci-job:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4.1.1
            - name: Run my own composite action
              id: my-action
              uses: ./
              with:
                who-to-greet: '@wulfland'
            - name: Output the answer
              run: echo "The answer is ${{ steps.my-action.outputs.answer }}"
                  